[start]
command:/usr/local/opnsense/scripts/lcdproc/setup.sh start
parameters:
type:script
message:starting lcdproc

[stop]
command:/usr/local/opnsense/scripts/lcdproc/setup.sh stop
parameters:
type:script
message:stopping lcdproc

[restart]
command:/usr/local/opnsense/scripts/lcdproc/setup.sh restart
parameters:
type:script
message:restarting lcdproc

[status]
command:/usr/local/opnsense/scripts/lcdproc/setup.sh status; exit 0
parameters:
type:script_output
message:request lcdproc status

[reconfigure]
command:/usr/local/sbin/configctl template reload OPNsense/LCDproc && /usr/local/opnsense/scripts/lcdproc/setup.sh restart
parameters:
type:script
message:reconfiguring lcdproc
description:Reconfigure LCDproc
